blank_issues_enabled: true
contact_links:
  - name: Security issue
    url: https://github.com/kode3tech/open-cicd-contract/security/policy
    about: Please avoid public disclosure. See SECURITY.md for guidance.
